### ISSUE TITLE
Not work with redmine 2.5.1

### ISSUE THREAD

**Issue by alexistoledo** [AllTaken/redmine_my_page_queries#3]
log file:

Processing by MyController#page as HTML
  Current user: xxxxxxxx (id=1)
  Rendered plugins/redmine_my_page_queries/app/views/my/blocks/_issues_custom_query_4.html.erb (72.6ms)
  Rendered my/page.html.erb within layouts/base (181.3ms)
Completed 500 Internal Server Error in 568.8ms

ActionController::RoutingError (No route matches {:action=>"", :controller=>"my"}):
  app/views/my/page.html.erb:11:in `block in _app_views_my_page_html_erb__1675618580121071768_31747140'
  app/views/my/page.html.erb:8:in `each'
  app/views/my/page.html.erb:8:in `_app_views_my_page_html_erb__1675618580121071768_31747140'

**Comment by AllTaken** [comment]
Will now work with 3.0.1 e2469268518bcbcb801f2fc44b51dfb523a89cf2
