### ISSUE TITLE
Not working with Redmine-3.3

### ISSUE THREAD

**Issue by peter17** [AllTaken/redmine_my_page_queries#4]
I have the following problem:

After I installed the plugin, I went to the page `/my/page` and customized this page (`/my/page_layout`). I added a block "Issues custom query 1" and saved.

Now, both `/my/page` and `/my/page_layout` return a 404 error so I cannot access them nor revert my change... I had to restore a backup of the database to be able to access my page again...

Can you please have a look at it? Thanks in advance. Best regards

**Comment by AllTaken** [comment]
It is working on 3.3.3.stable for me. I cannot reproduce your error.
