### ISSUE TITLE
Not working with redmine-3.4.3

### ISSUE THREAD

**Issue by jbedouet** [AllTaken/redmine_my_page_queries#5]
I have just upgraded my Redmine server to 3.4.3 and I have the following issue when clicking on my page or the issues of a project.

Thanks for any help,

J. Bedouet

Started GET "/" for 127.0.0.1 at 2017-11-19 21:49:50 +0100
Processing by WelcomeController#index as HTML
  Current user: redmine (id=1)
  Rendered news/_news.html.erb (8.8ms)
  Rendered welcome/index.html.erb within layouts/base (24.4ms)
Completed 200 OK in 82ms (Views: 31.4ms | ActiveRecord: 37.3ms)
Started GET "/my/page" for 127.0.0.1 at 2017-11-19 21:49:55 +0100
Processing by MyController#page as HTML
  Current user: redmine (id=1)
  Rendered queries/_columns.html.erb (3.5ms)
  Rendered my/blocks/_issues.erb (8.8ms)
  Rendered queries/_columns.html.erb (3.9ms)
  Rendered issues/_list.html.erb (4.0ms)
  Rendered my/blocks/_issues.erb (13.2ms)
  Rendered my/page.html.erb within layouts/base (102.0ms)
Completed 500 Internal Server Error in 119ms (ActiveRecord: 18.4ms)

ActionView::Template::Error (wrong number of arguments (given 3, expected 1)):
    11:         <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
    12:               :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
    13:       </th>
    14:       <% query.inline_columns.each do |column| %>
    15:         <%= column_header(query, column, query_options) %>
    16:       <% end %>
    17:     </tr>
  plugins/redmine_my_page_queries/lib/queries_helper_patch.rb:13:in `column_header_with_nilable_criteria'
  app/views/issues/_list.html.erb:14:in `block (2 levels) in _app_views_issues__list_html_erb__3524956707207338285_69936850223140'
  app/views/issues/_list.html.erb:13:in `each'
  app/views/issues/_list.html.erb:13:in `block in _app_views_issues__list_html_erb__3524956707207338285_69936850223140'
  app/views/issues/_list.html.erb:4:in `_app_views_issues__list_html_erb__3524956707207338285_69936850223140'
  app/views/my/blocks/_issues.erb:24:in `_app_views_my_blocks__issues_erb__837973105002064114_69936842729940'
  app/helpers/my_helper.rb:113:in `render_issuesreportedbyme_block'
  app/helpers/my_helper.rb:64:in `render_block_content'
  app/helpers/my_helper.rb:35:in `render_block'
  app/helpers/my_helper.rb:27:in `block in render_blocks'
  app/helpers/my_helper.rb:26:in `each'
  app/helpers/my_helper.rb:26:in `render_blocks'
  app/views/my/page.html.erb:13:in `block in _app_views_my_page_html_erb___3611685711570841743_69936844750340'
  app/views/my/page.html.erb:11:in `each'
  app/views/my/page.html.erb:11:in `_app_views_my_page_html_erb___3611685711570841743_69936844750340'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by AllTaken** [comment]
I don't think there is any reason to use this plugin with redmine 3.4.
The same functionality is now a part of standard Redmine: 
http://www.redmine.org/issues/1565

**Comment by jbedouet** [comment]
OK, I have just seen the different changes on My Page. Thanks.
